/* The gallery's eight sets. Each card: [category, title, duration, prompt, scene]. Data from site-v3/Gallery.dc.html. */

export type Card = [cat: string, title: string, dur: string, prompt: string, scene: string];
export type GallerySet = { name: string; short: string; id: string; intro?: string; cards: Card[] };

export const SETS: GallerySet[] = [
  {
    name: "Showcase",
    short: "Showcase",
    id: "showcase",
    intro: "The long ones. Full explainers and heavy renders, each still a single sentence away.",
    cards: [
      ["Explainer", "Why your room gets messy", "0:54", "explain entropy with a stick figure who just cleaned his room", "stickmess"],
      ["Explainer", "The hotel that is always full", "0:52", "explain Hilbert's hotel with a stick figure who just wants one room", "stickhotel"],
      ["Explainer", "Why you feel due for a win", "0:48", "explain the gambler's fallacy with a stick figure on a losing streak", "stickluck"],
      ["Explainer", "Why the other lane is faster", "0:44", "explain why the other lane looks faster with a stick figure stuck in traffic", "sticklane"],
      ["Explainer", "Always switch doors", "0:46", "explain the Monty Hall problem with a stick figure who does not trust the host", "stickdoors"],
      ["Explainer", "How not to fall into a black hole", "2:07", "explain black holes with a stick figure, and make it funny", "stickhole"],
      ["Symmetry", "Mandala, drawn once", "0:30", "mirror one wandering curve twelve ways until it blooms", "kaleido"],
      ["Astrophysics", "How a world gets made", "0:46", "start with a cloud of dust and end with a world someone could stand on", "origin"],
      ["L-systems", "A year in one tree", "0:34", "grow a tree from one seed and run it through four seasons", "tree"],
      ["Fields", "Northern lights", "0:30", "put the aurora over a frozen lake and let it drift", "aurora"],
      ["Procedural", "Flight over a range", "0:20", "fly me over mountains that were never surveyed", "terrain"],
      ["Astrophysics", "Supernova", "0:15", "blow up a star and follow the shockwave out", "supernova"],
      ["Astrophysics", "Nebula, condensing", "0:16", "grow an emission nebula out of the dark and light it up", "nebula"],
      ["Fluids", "Dye in a curl field", "0:16", "pour dye into a swirling field and let it draw", "curl"],
      ["Chaos", "Attractor, morphing", "0:18", "morph a de Jong attractor through its parameters", "dejong"],
      ["Neural nets", "A signal, crossing", "0:16", "send one signal through a small neural network", "neural"],
    ],
  },
  {
    name: "Fractals & self-similarity",
    short: "Fractals",
    id: "fractals",
    cards: [
      ["Fractals", "Sierpinski triangle", "", "cut a triangle out of a triangle, forever", "sierpinski"],
      ["Fractals", "Dragon curve", "", "fold one strip of paper twelve times and unfold it", "dragon"],
      ["Fractals", "Koch snowflake", "", "bend every edge into four, forever", "koch"],
      ["Fractals", "A fern from dice", "", "roll four matrices at random until a fern grows", "chaosgame"],
      ["Geometry", "Apollonian gasket", "", "pack a circle with circles until the gaps run out", "apollonian"],
      ["Geometry", "Hilbert curve", "", "fill a square with one unbroken line", "hilbert"],
    ],
  },
  {
    name: "Chaos & dynamics",
    short: "Chaos",
    id: "chaos",
    cards: [
      ["Chaos", "Rössler band", "", "draw the attractor that folds itself once", "rossler"],
      ["Chaos", "Islands of order", "", "sweep the standard map until order drowns", "standardmap"],
      ["Chaos", "The Lorenz butterfly", "", "trace the Lorenz attractor", "lorenz"],
      ["Chaos", "Butterfly effect", "", "nudge a double pendulum by 0.001 radians", "pendulum"],
      ["Chaos", "Route to chaos", "", "sweep r through the logistic map", "logistic"],
      ["Physics", "Three-body ballet", "", "make three planets orbit in a figure-8", "threebody"],
      ["Emergence", "Flocking", "", "give 130 birds three rules, then add a hawk", "boids"],
      ["Chaos", "Game of Life", "", "run Conway's rules on gliders and blinkers", "gameoflife"],
      ["Emergence", "Turing patterns", "", "let two chemicals fight until stripes appear", "turing"],
    ],
  },
  {
    name: "Algebra & geometry",
    short: "Algebra",
    id: "algebra",
    cards: [
      ["Topology", "Möbius band", "", "walk a Möbius strip and come back mirrored", "mobius"],
      ["Topology", "Torus knot", "", "spin a (3,7) knot around its torus", "torusknot"],
      ["Linear algebra", "Eigenvectors", "", "show which vectors keep their direction", "eigen"],
      ["Linear algebra", "Matrix transform", "", "shear a grid with a 2×2 matrix", "matrix"],
      ["Linear algebra", "Vector field flow", "", "animate a rotational vector field", "vfield"],
      ["Geometry", "Pythagorean proof", "", "prove a²+b² = c² by rearranging squares", "pyth"],
      ["Topology", "Square to hypercube", "", "unfold a square into 3D, then into 4D", "tesseract"],
      ["Geometry", "Golden spiral", "", "tile Fibonacci squares and sweep the spiral", "fib"],
      ["Geometry", "Sunflower spiral", "", "grow a sunflower with the golden angle", "phyllo"],
    ],
  },
  {
    name: "Numbers & chance",
    short: "Numbers",
    id: "numbers",
    cards: [
      ["Probability", "Benford's law", "", "count the first digit of six thousand real numbers", "benford"],
      ["Probability", "Birthday collisions", "", "fill a room until two people share a birthday", "birthday"],
      ["Geometry", "Spiral of primes", "", "plot primes on an Ulam spiral", "primes"],
      ["Number theory", "Times-table cardioid", "", "connect n to 2n around a circle, then sweep", "modular"],
      ["Number theory", "Hailstone numbers", "", "race five Collatz sequences down to 1", "collatz"],
      ["Number theory", "Sieve of Eratosthenes", "", "cross out the multiples, keep the primes", "sieve"],
      ["Probability", "Bell curve", "", "build a normal distribution from samples", "bell"],
      ["Probability", "Random walks", "", "flip coins and show the √n envelope", "walk"],
      ["Probability", "Estimating π with darts", "", "throw random darts at a square, count the circle", "montecarlo"],
    ],
  },
  {
    name: "Calculus & analysis",
    short: "Calculus",
    id: "calculus",
    cards: [
      ["Optimization", "Gradient descent", "", "race plain descent against momentum downhill", "gradient"],
      ["Calculus", "Area under a curve", "", "shade the Riemann sum under a parabola", "riemann"],
      ["Calculus", "Tangent line", "", "sweep the tangent along a cubic", "tangent"],
      ["Calculus", "Taylor series", "", "approximate sin(x) with polynomials", "taylor"],
      ["Calculus", "The limit definition", "", "slide h to zero until the secant kisses the curve", "limit"],
    ],
  },
  {
    name: "Circles & waves",
    short: "Waves",
    id: "waves",
    cards: [
      ["Trigonometry", "Lissajous sweep", "", "sweep a Lissajous figure through every ratio", "lissajous"],
      ["Physics", "Sonic boom", "", "circle a siren faster than its own sound", "doppler"],
      ["Trigonometry", "Sine from a circle", "", "trace a sine wave from a rotating circle", "sine"],
      ["Trigonometry", "Square wave from circles", "", "build a square wave by stacking spinning circles", "fourier"],
      ["Trigonometry", "Euler's identity", "", "walk e^iθ around the unit circle to −1", "euler"],
    ],
  },
  {
    name: "Space & physics",
    short: "Space",
    id: "space",
    cards: [
      ["Physics", "Precessing orbit", "", "let an orbit precess into a flower", "orbits"],
      ["Astrophysics", "Lensed light", "", "bend starlight around a black hole", "blackhole"],
      ["Physics", "Galaxy collision", "", "throw two galaxies through each other", "galaxy"],
      ["Physics", "Interference", "", "ripple two waves through each other", "waves"],
    ],
  },
];
